apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: metrics.cpupools.intel.com
spec:
  group: cpupools.intel.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: metrics
    singular: metric
    kind: Metric
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["pools"]
          properties:
            pools:
              description: A list of pool names and usage values.
              type: array
              properties:
                items:
                  properties:
                    poolName:
                      description: Name of the CPU pool
                      type: string
                    usage:
                      description: Pool usage value in millicores.
                      type: integer
                    capacity:
                      description: Pool capacity value in millicores.
                      type: integer
                    exclusive:
                      description: Exclusive CPUset
                      type: string
                    shared:
                      description: Shared CPUset
                      type: string
                  required:
                  - poolName
                  - usage
                  - capacity
                  - exclusive
                  - shared
