apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-cpu-pool-plugin
  namespace: kube-system
  labels:
    app: intel-cpu-pool-plugin
spec:
  selector:
    matchLabels:
      app: intel-cpu-pool-plugin
  template:
    metadata:
      labels:
        app: intel-cpu-pool-plugin
    spec:
      containers:
      - name: intel-cpu-pool-plugin
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: intel-cpu-pool-policy:devel
        command: ["/usr/bin/intel_cpu_pool_policy"]
        args: ["-logtostderr"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          - name: kubeletsockets
            mountPath: /var/lib/kubelet/cpu-plugin
      volumes:
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/cpu-plugin
      - name: config-volume
        configMap:
          name: cpu-pool-plugin-config
